In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
df=pd.read_csv('/content/drive/MyDrive/new_train_sample.csv')

In [ ]:
pd.set_option('display.max_columns', None)

In [ ]:
df.head(5)

Unnamed: 0             Id  OrgId  IncidentId  AlertId  \
0     5172780  1709396985476     26       18583   687462   
1     8470561   927712939180     33        5065     3990   
2     5897583  1090921697002    201      150787   807590   
3     3288552  1434519079555    204      108287    28575   
4     4060961  1005022347708     54      528202  1458226   

                  Timestamp  DetectorId  AlertTitle            Category  \
0  2024-06-06T05:56:47.000Z          31         813             Malware   
1  2024-06-03T10:45:09.000Z          38          25              Impact   
2  2024-06-13T03:36:40.000Z         419         444           Execution   
3  2024-06-08T16:54:57.000Z          44        1233  SuspiciousActivity   
4  2024-06-09T02:48:01.000Z         102       58829        Exfiltration   

                                     MitreTechniques   IncidentGrade  \
0                                                NaN  BenignPositive   
1                                                NaN  BenignPositive   
2  T1047;T1059;T1053;T1569;T1059.001;T1053.002;T1...  BenignPositive   
3                                                NaN    TruePositive   
4                                                NaN  BenignPositive   

  ActionGrouped ActionGranular EntityType EvidenceRole  DeviceId  Sha256  \
0           NaN            NaN       File      Related     98799    1296   
1           NaN            NaN    Machine     Impacted     98799  138268   
2           NaN            NaN    Machine     Impacted     98799  138268   
3           NaN            NaN       File      Related     98799  138268   
4           NaN            NaN       File     Impacted     98799  138268   

   IpAddress     Url  AccountSid  AccountUpn  AccountObjectId  AccountName  \
0     360606  160396      441377      673934           425863       453297   
1     360606  160396      441377      673934           425863       453297   
2     360606  160396      441377      673934           425863       453297   
3     360606  160396      441377      673934           425863       453297   
4     360606  160396      441377      673934           425863       453297   

   DeviceName  NetworkMessageId  EmailClusterId  RegistryKey  \
0      153085            529644             NaN         1631   
1        3142            529644             NaN         1631   
2        4181            529644             NaN         1631   
3      153085            529644             NaN         1631   
4      153085            529644             NaN         1631   

   RegistryValueName  RegistryValueData  ApplicationId  ApplicationName  \
0                635                860           2251             3421   
1                635                860           2251             3421   
2                635                860           2251             3421   
3                635                860           2251             3421   
4                635                860           2251             3421   

   OAuthApplicationId ThreatFamily  FileName  FolderPath  ResourceIdName  \
0                 881       Casdet      4132        4227            3586   
1                 881          NaN    289573      117668            3586   
2                 881          NaN    289573      117668            3586   
3                 881          NaN     97007        9177            3586   
4                 881          NaN     39978      114449            3586   

  ResourceType        Roles  OSFamily  OSVersion AntispamDirection  \
0          NaN          NaN         5         66               NaN   
1          NaN          NaN         5         66               NaN   
2          NaN  Destination         5         66               NaN   
3          NaN          NaN         5         66               NaN   
4          NaN          NaN         5         66               NaN   

  SuspicionLevel LastVerdict  CountryCode  State   City  
0     Suspicious   Malicious          242   1445  10630  
1 

In [ ]:
df.isnull().sum()

Unnamed: 0                  0
Id                          0
OrgId                       0
IncidentId                  0
AlertId                     0
Timestamp                   0
DetectorId                  0
AlertTitle                  0
Category                    0
MitreTechniques       2733136
IncidentGrade           25775
ActionGrouped         4730205
ActionGranular        4730205
EntityType                  0
EvidenceRole                0
DeviceId                    0
Sha256                      0
IpAddress                   0
Url                         0
AccountSid                  0
AccountUpn                  0
AccountObjectId             0
AccountName                 0
DeviceName                  0
NetworkMessageId            0
EmailClusterId        4710241
RegistryKey                 0
RegistryValueName           0
RegistryValueData           0
ApplicationId               0
ApplicationName             0
OAuthApplicationId          0
ThreatFamily          4721038
FileName                    0
FolderPath                  0
ResourceIdName              0
ResourceType          4754863
Roles                 4649117
OSFamily                    0
OSVersion                   0
AntispamDirection     4669846
SuspicionLevel        4037145
LastVerdict           3642221
CountryCode                 0
State                       0
City                        0
dtype: int64

In [ ]:
#droping columns having null above 40 percent
forty_percent= (40*len(df))/100
for columns in df.columns:
    if df[columns].isnull().sum() > forty_percent:
        df.drop(columns=[columns],inplace=True)

In [ ]:
df.head(5)

Unnamed: 0             Id  OrgId  IncidentId  AlertId  \
0     5172780  1709396985476     26       18583   687462   
1     8470561   927712939180     33        5065     3990   
2     5897583  1090921697002    201      150787   807590   
3     3288552  1434519079555    204      108287    28575   
4     4060961  1005022347708     54      528202  1458226   

                  Timestamp  DetectorId  AlertTitle            Category  \
0  2024-06-06T05:56:47.000Z          31         813             Malware   
1  2024-06-03T10:45:09.000Z          38          25              Impact   
2  2024-06-13T03:36:40.000Z         419         444           Execution   
3  2024-06-08T16:54:57.000Z          44        1233  SuspiciousActivity   
4  2024-06-09T02:48:01.000Z         102       58829        Exfiltration   

    IncidentGrade EntityType EvidenceRole  DeviceId  Sha256  IpAddress  \
0  BenignPositive       File      Related     98799    1296     360606   
1  BenignPositive    Machine     Impacted     98799  138268     360606   
2  BenignPositive    Machine     Impacted     98799  138268     360606   
3    TruePositive       File      Related     98799  138268     360606   
4  BenignPositive       File     Impacted     98799  138268     360606   

      Url  AccountSid  AccountUpn  AccountObjectId  AccountName  DeviceName  \
0  160396      441377      673934           425863       453297      153085   
1  160396      441377      673934           425863       453297        3142   
2  160396      441377      673934           425863       453297        4181   
3  160396      441377      673934           425863       453297      153085   
4  160396      441377      673934           425863       453297      153085   

   NetworkMessageId  RegistryKey  RegistryValueName  RegistryValueData  \
0            529644         1631                635                860   
1            529644         1631                635                860   
2            529644         1631                635                860   
3            529644         1631                635                860   
4            529644         1631                635                860   

   ApplicationId  ApplicationName  OAuthApplicationId  FileName  FolderPath  \
0           2251             3421                 881      4132        4227   
1           2251             3421                 881    289573      117668   
2           2251             3421                 881    289573      117668   
3           2251             3421                 881     97007        9177   
4           2251             3421                 881     39978      114449   

   ResourceIdName  OSFamily  OSVersion  CountryCode  State   City  
0            3586         5         66          242   1445  10630  
1            3586         5         66          242   1445  10630  
2            3586         5         66          242   1445  10630  
3            3586         5         66          242   1445  10630  
4            3586         5         66          242   1445  10630

In [ ]:
df.isnull().sum()

In [ ]:
#since IncidentGrade is the target column and only columns left with null values
# imputing the null will affect the accuracy of the model
df=df.dropna()

In [ ]:
df['IncidentGrade'].unique()

array(['BenignPositive', 'TruePositive', 'FalsePositive'], dtype=object)

In [ ]:
df['day']=pd.to_datetime(df['Timestamp']).dt.day
df['month']=pd.to_datetime(df['Timestamp']).dt.month
df['year']=pd.to_datetime(df['Timestamp']).dt.year
df['hour']=pd.to_datetime(df['Timestamp']).dt.hour
df['minute']=pd.to_datetime(df['Timestamp']).dt.minute
df['second']=pd.to_datetime(df['Timestamp']).dt.second
df.drop(columns=['Unnamed: 0','Timestamp'],inplace=True)#dropping the unnecessary columns

In [ ]:
df.head(5)

Id  OrgId  IncidentId  AlertId  DetectorId  AlertTitle  \
0  1709396985476     26       18583   687462          31         813   
1   927712939180     33        5065     3990          38          25   
2  1090921697002    201      150787   807590         419         444   
3  1434519079555    204      108287    28575          44        1233   
4  1005022347708     54      528202  1458226         102       58829   

             Category   IncidentGrade EntityType EvidenceRole  DeviceId  \
0             Malware  BenignPositive       File      Related     98799   
1              Impact  BenignPositive    Machine     Impacted     98799   
2           Execution  BenignPositive    Machine     Impacted     98799   
3  SuspiciousActivity    TruePositive       File      Related     98799   
4        Exfiltration  BenignPositive       File     Impacted     98799   

   Sha256  IpAddress     Url  AccountSid  AccountUpn  AccountObjectId  \
0    1296     360606  160396      441377      673934           425863   
1  138268     360606  160396      441377      673934           425863   
2  138268     360606  160396      441377      673934           425863   
3  138268     360606  160396      441377      673934           425863   
4  138268     360606  160396      441377      673934           425863   

   AccountName  DeviceName  NetworkMessageId  RegistryKey  RegistryValueName  \
0       453297      153085            529644         1631                635   
1       453297        3142            529644         1631                635   
2       453297        4181            529644         1631                635   
3       453297      153085            529644         1631                635   
4       453297      153085            529644         1631                635   

   RegistryValueData  ApplicationId  ApplicationName  OAuthApplicationId  \
0                860           2251             3421                 881   
1                860           2251             3421                 881   
2                860           2251             3421                 881   
3                860           2251             3421                 881   
4                860           2251             3421                 881   

   FileName  FolderPath  ResourceIdName  OSFamily  OSVersion  CountryCode  \
0      4132        4227            3586         5         66          242   
1    289573      117668            3586         5         66          242   
2    289573      117668            3586         5         66          242   
3     97007        9177            3586         5         66          242   
4     39978      114449            3586         5         66          242   

   State   City  day  month  year  hour  minute  second  
0   1445  10630    6      6  2024     5      56      47  
1   1445  10630    3      6  2024    10      45       9  
2   1445  10630   13      6  2024     3      36      40  
3   1445  10630    8      6  2024    16      54      57  
4   1445  10630    9      6  2024     2      48       1

# **Scaling**

In [ ]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
list_of_columns = ['day', 'month', 'year', 'hour', 'minute', 'second']


df[list_of_columns]=scaler.fit_transform(df[list_of_columns])


# **Encoding**

In [ ]:
ef=df.drop(columns=['day', 'month', 'year', 'hour', 'minute', 'second','IncidentGrade'])

from sklearn.preprocessing import LabelEncoder
# Label Encoding
label_encoder = LabelEncoder()

for i in ef.columns:
  df[i]=label_encoder.fit_transform(df[i])

In [ ]:
df

Id  OrgId  IncidentId  AlertId  DetectorId  AlertTitle  Category  \
0        640132     25       16628   557537          30         776        12   
1        348676     32        4475     3132          37          25         9   
2        409923    199      133879   634189         394         425         6   
3        538223    201       97713    22518          43        1152        16   
4        375805     53      392753  1033243          98       46545         7   
...         ...    ...         ...      ...         ...         ...       ...   
4758413   38683    141       85148    12165         108        6852         7   
4758414  632174     35         798   215349           2           2         1   
4758415  598771    841       28097  1068801           1           1        10   
4758416   53428     12        2088     1066          16        1232         9   
4758417  461596    199       36091   490569           5          97        16   

          IncidentGrade  EntityType  EvidenceRole  ...  OSVersion  \
0        BenignPositive           9             1  ...         47   
1        BenignPositive          17             0  ...         47   
2        BenignPositive          17             0  ...         47   
3          TruePositive           9             1  ...         47   
4        BenignPositive           9             0  ...         47   
...                 ...         ...           ...  ...        ...   
4758413   FalsePositive          19             0  ...         47   
4758414   FalsePositive          30             0  ...         47   
4758415  BenignPositive          19             1  ...         47   
4758416  BenignPositive          13             1  ...         47   
4758417  BenignPositive           5             0  ...         47   

         CountryCode  State  City       day     month  year      hour  \
0                211   1196  7106  0.166667  0.454545   1.0  0.217391   
1                211   1196  7106  0.066667  0.454545   1.0  0.434783   
2                211   1196  7106  0.400000  0.454545   1.0  0.130435   
3                211   1196  7106  0.233333  0.454545   1.0  0.695652   
4                211   1196  7106  0.266667  0.454545   1.0  0.086957   
...              ...    ...   ...       ...       ...   ...       ...   
4758413          211   1196  7106  0.300000  0.454545   1.0  0.434783   
4758414          211   1196  7106  0.333333  0.454545   1.0  0.826087   
4758415          211   1196  7106  0.266667  0.454545   1.0  0.173913   
4758416          211   1196  7106  0.666667  0.363636   1.0  1.000000   
4758417          211   1196  7106  0.400000  0.454545   1.0  0.521739   

           minute    second  
0        0.949153  0.796610  
1        0.762712  0.152542  
2        0.610169  0.677966  
3        0.915254  0.966102  
4        0.813559  0.016949  
...           ...       ...  
4758413  0.423729  0.288136  
4758414  0.508475  0.881356  
4758415  0.457627  0.694915  
4758416  0.016949  0.186441  
4758417  0.135593  0.508475  

[4732643 rows x 40 columns]

# RandomForestfor feature importance

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import pandas as pd
import numpy as np

# feature and target
X = df.drop(columns=["IncidentGrade"])
y = df["IncidentGrade"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
rf_clf = RandomForestClassifier(n_estimators=100, random_state=42)
rf_clf.fit(X_train, y_train)
importances = rf_clf.feature_importances_
feature_names = X.columns
feature_importances = pd.DataFrame({'Feature': feature_names, 'Importance': importances})
feature_importances = feature_importances.sort_values(by='Importance', ascending=False)


In [ ]:
feature_importances

Feature  Importance
1                OrgId    0.228995
2           IncidentId    0.140852
4           DetectorId    0.104370
3              AlertId    0.090881
5           AlertTitle    0.082256
6             Category    0.039854
33                 day    0.038534
0                   Id    0.034958
36                hour    0.021711
7           EntityType    0.021474
38              second    0.020296
37              minute    0.020147
14          AccountUpn    0.018273
13          AccountSid    0.014228
30         CountryCode    0.013274
15     AccountObjectId    0.013015
11           IpAddress    0.011417
16         AccountName    0.011183
18    NetworkMessageId    0.009856
31               State    0.008132
17          DeviceName    0.007546
26          FolderPath    0.006720
25            FileName    0.006596
32                City    0.006243
12                 Url    0.005802
10              Sha256    0.005674
8         EvidenceRole    0.004797
34               month    0.003585
9             DeviceId    0.003370
23     ApplicationName    0.001718
22       ApplicationId    0.001640
19         RegistryKey    0.000905
29           OSVersion    0.000737
28            OSFamily    0.000628
27      ResourceIdName    0.000157
21   RegistryValueData    0.000073
20   RegistryValueName    0.000054
24  OAuthApplicationId    0.000035
35                year    0.000014

# Decision tree

In [ ]:
ef = pd.concat([df[df['IncidentGrade'] == 'FalsePositive'].iloc[:1015782],
                df[df['IncidentGrade'] == 'TruePositive'].iloc[:1015782],
                df[df['IncidentGrade'] == 'BenignPositive'].iloc[:1015782]])

from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import pandas as pd
import numpy as np
# Separate features and target variable
X = ef[['OrgId', 'IncidentId', 'DetectorId', 'AlertId', 'AlertTitle', 'Category','day','hour']]
y = ef["IncidentGrade"]

# Split into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

dt_clf = DecisionTreeClassifier(max_depth=10, random_state=42)
dt_clf.fit(X_train, y_train)

# Predict on the test set
y_pred = dt_clf.predict(X_test)

# Accuracy score
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")

# Classification report
print(classification_report(y_test, y_pred))

# Confusion matrix
print(confusion_matrix(y_test, y_pred))


Accuracy: 0.75
                precision    recall  f1-score   support

BenignPositive       0.62      0.87      0.72    305097
 FalsePositive       0.77      0.70      0.73    304683
  TruePositive       0.97      0.67      0.80    304424

      accuracy                           0.75    914204
     macro avg       0.79      0.75      0.75    914204
  weighted avg       0.79      0.75      0.75    914204

[[264593  37484   3020]
 [ 89032 212898   2753]
 [ 71989  26975 205460]]


# Logistic Regression

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import pandas as pd
import numpy as np

ef = pd.concat([df[df['IncidentGrade'] == 'FalsePositive'],
                df[df['IncidentGrade'] == 'TruePositive'].iloc[:1015782],
                df[df['IncidentGrade'] == 'BenignPositive'].iloc[:1015782]])

# Separate features and target variable
X = ef[['OrgId', 'IncidentId', 'DetectorId', 'AlertId', 'AlertTitle', 'Category','day','hour']]
y = ef["IncidentGrade"]

# Split into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Initialize and train the Logistic Regression model
log_reg = LogisticRegression(max_iter=1000, random_state=42)
log_reg.fit(X_train, y_train)

# Predict on the test set
y_pred = log_reg.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Accuracy: 0.48
                precision    recall  f1-score   support

BenignPositive       0.43      0.30      0.35    305097
 FalsePositive       0.40      0.52      0.45    304683
  TruePositive       0.63      0.62      0.62    304424

      accuracy                           0.48    914204
     macro avg       0.48      0.48      0.48    914204
  weighted avg       0.48      0.48      0.48    914204

[[ 91059 155747  58291]
 [ 90668 159666  54349]
 [ 28371  87991 188062]]



# Random Forest

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import pandas as pd
import numpy as np

# Separate features and target variable
X = df.drop(columns=["IncidentGrade"])
y = df["IncidentGrade"]

# Split into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Initialize and train the Random Forest model
rf_clf = RandomForestClassifier(n_estimators=100, random_state=42)
rf_clf.fit(X_train, y_train)

# Predict on the test set
y_pred = rf_clf.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")
print(classification_report(y_test, y_pred))


Accuracy: 0.98
                precision    recall  f1-score   support

BenignPositive       0.97      0.99      0.98    616698
 FalsePositive       0.97      0.96      0.96    304431
  TruePositive       0.99      0.97      0.98    498664

      accuracy                           0.98   1419793
     macro avg       0.98      0.97      0.97   1419793
  weighted avg       0.98      0.98      0.98   1419793



In [ ]:
#but the above model over fits

# taking equal data for all the classes in target

In [ ]:
ef = pd.concat([df[df['IncidentGrade'] == 'FalsePositive'],
                df[df['IncidentGrade'] == 'TruePositive'].iloc[:1015782],
                df[df['IncidentGrade'] == 'BenignPositive'].iloc[:1015782]])

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import pandas as pd
import numpy as np

# Separate features and target variable
X = ef[[
    'OrgId', 'IncidentId', 'DetectorId', 'AlertId', 'AlertTitle',
    'Category', 'day', 'Id', 'hour', 'EntityType',
    'second', 'minute', 'AccountUpn', 'AccountSid', 'CountryCode'
]]
y = ef["IncidentGrade"]

# Split into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=42,stratify=y)

# Initialize and train the Random Forest model
rf_clf = RandomForestClassifier(n_estimators=100, random_state=42)
rf_clf.fit(X_train, y_train)

# Predict on the test set
y_pred = rf_clf.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")
print(classification_report(y_test, y_pred))


Accuracy: 0.98
                precision    recall  f1-score   support

BenignPositive       0.98      0.98      0.98    406313
 FalsePositive       0.97      0.98      0.98    406313
  TruePositive       0.99      0.97      0.98    406313

      accuracy                           0.98   1218939
     macro avg       0.98      0.98      0.98   1218939
  weighted avg       0.98      0.98      0.98   1218939



# Random forest with regularization parameters

In [ ]:
ef = pd.concat([df[df['IncidentGrade'] == 'FalsePositive'].iloc[:1015782],
                df[df['IncidentGrade'] == 'TruePositive'].iloc[:1015782],
                df[df['IncidentGrade'] == 'BenignPositive'].iloc[:1015782]])

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import pandas as pd
import numpy as np

# Separate features and target variable
X = ef[[
    'OrgId', 'IncidentId', 'DetectorId', 'AlertId', 'AlertTitle',
    'Category']]
y = ef["IncidentGrade"]

# Split into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42,stratify=y)

# Initialize RandomForest with regularization parameters
rf_clf = RandomForestClassifier(
    n_estimators=50,
    max_depth=10,           # Limiting tree depth to prevent overfitting
    min_samples_split=5,    # Require more samples for splits
    min_samples_leaf=4,     # Minimum samples per leaf to prevent small leaf nodes
    max_features='sqrt',    # Limit number of features for splits
    random_state=42
)
rf_clf.fit(X_train, y_train)

# Predict on the test set
y_pred = rf_clf.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")
print(classification_report(y_test, y_pred))


Accuracy: 0.81
                precision    recall  f1-score   support

BenignPositive       0.69      0.93      0.79    203156
 FalsePositive       0.87      0.77      0.81    203157
  TruePositive       0.97      0.75      0.84    203157

      accuracy                           0.81    609470
     macro avg       0.84      0.81      0.82    609470
  weighted avg       0.84      0.81      0.82    609470



In [ ]:
import pickle

path='/content/drive/MyDrive/eq1_model.pkl'
# Pickle the model
with open(path, "wb") as file:
    pickle.dump(rf_clf, file)

print('the model file  is pickled ')

the model file  is pickled 


# Gradient boosting

In [ ]:
ef = pd.concat([df[df['IncidentGrade'] == 'FalsePositive'].iloc[:1015782],
                df[df['IncidentGrade'] == 'TruePositive'].iloc[:1015782],
                df[df['IncidentGrade'] == 'BenignPositive'].iloc[:1015782]])

from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Separate features and target variable
X = ef[['OrgId', 'IncidentId', 'DetectorId', 'AlertId', 'AlertTitle', 'Category']]
y = ef["IncidentGrade"]

# Split into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# Initialize the Gradient Boosting Classifier
gb_clf = GradientBoostingClassifier(n_estimators=100, random_state=42)

# Train the model
gb_clf.fit(X_train, y_train)

# Predict on the test set
y_pred = gb_clf.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))



Accuracy: 0.81
                precision    recall  f1-score   support

BenignPositive       0.74      0.86      0.80    203156
 FalsePositive       0.81      0.81      0.81    203157
  TruePositive       0.92      0.77      0.84    203157

      accuracy                           0.81    609470
     macro avg       0.82      0.81      0.82    609470
  weighted avg       0.82      0.81      0.82    609470

[[173962  22890   6304]
 [ 30128 164881   8148]
 [ 29836  16064 157257]]


In [ ]:
import pickle

path='/content/drive/MyDrive/gb_model.pkl'
# Pickle the model
with open(path, "wb") as file:
    pickle.dump(gb_clf, file)

print('the model file  is pickled ')

the model file  is pickled 


knn

In [ ]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

ef = pd.concat([df[df['IncidentGrade'] == 'FalsePositive'].iloc[:1015782],
                df[df['IncidentGrade'] == 'TruePositive'].iloc[:1015782],
                df[df['IncidentGrade'] == 'BenignPositive'].iloc[:1015782]])

# Separate features and target variable
X = ef[['OrgId', 'IncidentId', 'DetectorId', 'AlertId', 'AlertTitle', 'Category']]
y = ef["IncidentGrade"]

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Feature scaling
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Initialize the KNN classifier with k=3
k = 3
knn = KNeighborsClassifier(n_neighbors=k)

# Train the model
knn.fit(X_train, y_train)

# Make predictions
y_pred = knn.predict(X_test)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy of KNN with k={k}: {accuracy:.2f}")

# Print the classification report
print(classification_report(y_test, y_pred))


Accuracy of KNN with k=3: 0.96
                precision    recall  f1-score   support

BenignPositive       0.96      0.96      0.96    202895
 FalsePositive       0.96      0.97      0.96    203433
  TruePositive       0.97      0.97      0.97    203142

      accuracy                           0.96    609470
     macro avg       0.96      0.96      0.96    609470
  weighted avg       0.96      0.96      0.96    609470



In [ ]:
import pickle

path='/content/drive/MyDrive/knn_model.pkl'
# Pickle the model
with open(path, "wb") as file:
    pickle.dump(knn, file)

print('the model file  is pickled ')

the model file  is pickled 
